Closes #296 - Implement functionality that is required for sending information from Contact us form on web to an e-mail adress that should be specified in a configurational file
koldovsky/orlp-server pull request #298
Opened 2018-10-31 17:40 UTC by maxturko

2018-10-31 17:45 UTC, maxturko commented
Need to rewrite LOGGER input values and method descriptions in the interface

2018-11-01 06:41 UTC, antonbakalets commented on src/main/java/com/softserve/academy/spaced/repetition/controller/dto/simpleDTO/MailDTO.java
> +package com.softserve.academy.spaced.repetition.controller.dto.simpleDTO;
The best solution would be to create a separate PR that just do the renaming.

2018-11-01 06:45 UTC, antonbakalets requested changes

2018-11-01 06:45 UTC, antonbakalets commented on src/main/java/com/softserve/academy/spaced/repetition/service/MailService.java
> +    String contactUsMailTemplateContent(Map<String, Object> model);
As I understand this method is a private method of service implementation (MailServiceImpl.java). There is no need to expose it through the interface.
If something can be private - make it private (encapsulation).

2018-11-01 10:18 UTC, maxturko commented on src/main/java/com/softserve/academy/spaced/repetition/controller/dto/simpleDTO/MailDTO.java
> +package com.softserve.academy.spaced.repetition.controller.dto.simpleDTO;
Do I need to propose changes to product owner in this case ?

2018-11-01 10:33 UTC, antonbakalets commented on src/main/java/com/softserve/academy/spaced/repetition/controller/dto/simpleDTO/MailDTO.java
> +package com.softserve.academy.spaced.repetition.controller.dto.simpleDTO;
No, as such it doesn't change the application behaviour.

2018-11-01 20:42 UTC, antonbakalets approved these changes

2018-11-02 08:35 UTC, OleksandrBartosh approved these changes

2018-11-02 10:21 UTC, volodymyrglynka approved these changes

2018-11-02 10:32 UTC, hlibOstapenko approved these changes

2018-11-02 10:41 UTC, merged