Closes #354 - Refactor google sign in
koldovsky/orlp-server pull request #360
Opened 2018-12-05 13:51 UTC by OleksandrMazur

2018-12-06 06:33 UTC, antonbakalets commented on src/main/java/com/softserve/academy/spaced/repetition/utils/validators/PasswordNotNullValidator.java
> +        /**
Please move the JavaDoc out of method body. It should be writen before the method.

2018-12-06 06:38 UTC, antonbakalets commented on src/main/java/com/softserve/academy/spaced/repetition/utils/validators/PasswordNotNullValidator.java
> +        boolean valid = false;
i like to write this kind of logical calculations in one line, like
```
return account.getAuthenticationType().equals(AuthenticationType.GOOGLE)
                || account.getAuthenticationType().equals(AuthenticationType.FACEBOOK)
                || (account.getPassword() != null;
```

You can try too.

2018-12-06 06:39 UTC, antonbakalets commented on src/main/java/com/softserve/academy/spaced/repetition/utils/validators/annotations/PasswordNotNull.java
> +@Target({ElementType.TYPE, ElementType.METHOD, ElementType.FIELD, ElementType.PARAMETER})
I believe this annotation is expected only on class level.

2018-12-14 09:16 UTC, antonbakalets requested changes

2018-12-14 09:16 UTC, antonbakalets commented on src/main/java/com/softserve/academy/spaced/repetition/service/UserService.java
> +    void validateAccount(Account account) throws PasswordCannotBeNullException;
This method is called only inside the service implementation, therefore it should be removed from interface and marked private.
Please also move the JavaDoc.

2018-12-14 09:37 UTC, antonbakalets approved these changes

2018-12-14 10:26 UTC, OlehPaliuh approved these changes

2018-12-14 12:18 UTC, OleksandrBartosh approved these changes

2018-12-15 11:23 UTC, merged